#!/bin/sh

grep -v "#" ~/src/scripts/unicode | dmenu -i -l 20 -fn 'Iosevka Slab:size=10:style=Regular' -nb '#222222' -nf '#bbbbbb' -sb '#363759' -sf '#eeeeee'  | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard

pgrep -x dunst >/dev/null && notify-send "$(xclip -o -selection clipboard) copied to clipboard."
