#!/bin/bash
# Gives a dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.
pgrep -x dmenu && exit
COLS="name,type,size,mountpoint"

drives="$(lsblk -rpo "$COLS" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"
[ -z "$drives" ] && exit 1
chosen="$(echo "$drives" | rofi -dmenu -i -p "Mount which drive?" | awk '{print $1}')"
[ -z "$chosen" ] && exit 1
# sudo -A mount "$chosen" && exit 0
# You may want to change the line below for more suggestions for mounting.
# I.e. you can increase the depth of the search, or add directories.
# This will increase the load time briefly though.
#mp="$(find /home/kevin/Mounts -type d -maxdepth 1 -printf "%f\n" 2>/dev/null | tail +2 2>/dev/null | dmenu -i -p "Enter mount point:")"
#[ "$mp" = "" ] && exit 1
#if [ ! -d "/home/kevin/Mounts/$mp" ]; then
#	mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$mp does not exist. Create it?")
#	[ "$mkdiryn" = "Yes" ] && mkdir -p "/home/kevin/Mounts/$mp"
#fi
#sudo -A mount "$chosen" "/home/kevin/Mounts/$mp" -o uid=1000,gid=1000 && pgrep -x dunst && notify-send "$chosen -> /home/kevin/Mounts/$mp"

udisksctl mount -b "$chosen" |& xargs -0 notify-send -t 3000
